pipeline {
    agent any
    
    stages {
        stage('Download Dockerfile') {
            steps {
                script {
                    bat 'curl -o Dockerfile  https://tidy-definitely-sailfish.ngrok-free.app/clients/124160661/683c9c2803ce7d2f45cd8cd7/Dockerfile'
                }
            }
        }

        stage('Clone repo') {
            steps {
                git url: 'https://github.com/0marMejdi/BloggyDotTN', branch: 'master'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat 'docker build -t idpx/683c9c2803ce7d2f45cd8cd7 .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials(
                        [usernamePassword(
                            credentialsId: 'dockerhub-IDP-X' , 
                            usernameVariable: 'DOCKERHUB_USER', 
                            passwordVariable: 'DOCKERHUB_PASS'
                        )]){
                           bat '''
                            echo %DOCKERHUB_PASS% | docker login -u %DOCKERHUB_USER% --password-stdin
                            docker push idpx/683c9c2803ce7d2f45cd8cd7:latest
                            '''
                            }
                        }
            }
        }
    }
}