pipeline {
    agent any
    
    stages {
        stage('Download Files') {
            steps {
                script {
                    bat 'curl  -o Dockerfile  https://tidy-definitely-sailfish.ngrok-free.app/clients/124160661/683cf4b1e78762bbc3c4045a/Dockerfile'
                    
                    bat 'curl  -o main.tf  https://tidy-definitely-sailfish.ngrok-free.app/clients/124160661/683cf4b1e78762bbc3c4045a/main.tf'
                    
                }
            }
        }

        stage('Clone repo') {
            steps {
                git url: 'https://github.com/0marMejdi/ConsommiDotTN-Frontend', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat 'docker build -t idpx/683cf4b1e78762bbc3c4045a .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials(
                        [usernamePassword(
                            credentialsId: 'dockerhub-IDP-X' , 
                            usernameVariable: 'DOCKERHUB_USER', 
                            passwordVariable: 'DOCKERHUB_PASS'
                        )]){
                           bat '''
                            echo %DOCKERHUB_PASS% | docker login -u %DOCKERHUB_USER% --password-stdin
                            docker push idpx/683cf4b1e78762bbc3c4045a:latest
                            '''
                        }
                }
            }
        }

        
        stage('Initialize Terraform') {
            steps {
                script {
                    bat 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    bat 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    bat 'terraform apply -auto-approve tfplan'
                }
            }
        }
        
    }
}