pipeline {
    agent any
    
    stages {
        stage('Download Dockerfile') {
            steps {
                script {
                    bat 'curl --fail --retry 3 --retry-delay 2 -o Dockerfile  https://tidy-definitely-sailfish.ngrok-free.app/clients/124160661/683ce782cadbe51b2e247bbb/Dockerfile'
                }
            }
        }

        stage('Clone repo') {
            steps {
                git url: 'https://github.com/0marMejdi/ConsommiDotTN', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat 'docker build -t idpx/683ce782cadbe51b2e247bbb .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials(
                        [usernamePassword(
                            credentialsId: 'dockerhub-IDP-X' , 
                            usernameVariable: 'DOCKERHUB_USER', 
                            passwordVariable: 'DOCKERHUB_PASS'
                        )]){
                           bat '''
                            echo %DOCKERHUB_PASS% | docker login -u %DOCKERHUB_USER% --password-stdin
                            docker push idpx/683ce782cadbe51b2e247bbb:latest
                            '''
                            }
                        }
            }
        }
    }
}